const assert = require('node:assert/strict');
const { randomUUID } = require('node:crypto');

const baseUrl = String(process.env.ZHIQU_API_BASE_URL || 'http://127.0.0.1:18080').replace(/\/+$/, '');

async function request(path, { method = 'GET', token, body } = {}) {
  const headers = { Accept: 'application/json' };
  if (token) headers.Authorization = `Bearer ${token}`;
  if (body !== undefined) headers['Content-Type'] = 'application/json';
  const response = await fetch(`${baseUrl}${path}`, {
    method,
    headers,
    body: body === undefined ? undefined : JSON.stringify(body),
  });
  const text = await response.text();
  let payload = null;
  try { payload = text ? JSON.parse(text) : null; } catch { payload = text; }
  return { status: response.status, payload };
}

async function register(prefix, nickname) {
  const suffix = randomUUID().replaceAll('-', '').slice(0, 10);
  const response = await request('/api/auth/register', {
    method: 'POST',
    body: { username: `${prefix}${suffix}`, password: 'SafePass123!', nickname },
  });
  assert.equal(response.status, 201, `register ${prefix}`);
  return response.payload;
}

(async () => {
  const unauthenticated = await request('/api/assistant/config');
  assert.equal(unauthenticated.status, 401, 'assistant config must require login');

  const alice = await register('assist', '小知');
  const bob = await register('assistb', '小问');
  const token = alice.accessToken;

  const config = await request('/api/assistant/config', { token });
  assert.equal(config.status, 200);
  assert.equal(config.payload.longTermMemoryDefault, false);
  assert.equal(config.payload.maxMessageCharacters, 2000);

  const liveRecommendations = await request('/api/assistant/recommendations', { token });
  assert.equal(liveRecommendations.status, 200);
  assert.ok(Array.isArray(liveRecommendations.payload));
  assert.ok(liveRecommendations.payload.every((item) => item.contentId && item.href === `/content/${item.contentId}`));

  if (!config.payload.configured) {
    const unavailable = await request('/api/assistant/conversations', {
      method: 'POST', token, body: { memoryEnabled: false },
    });
    assert.equal(unavailable.status, 503, 'missing AI config must not return a fake greeting');
    assert.equal(unavailable.payload.code, 'AI_NOT_CONFIGURED');
    const empty = await request('/api/assistant/conversations', { token });
    assert.deepEqual(empty.payload, [], 'failed greeting must not create a conversation');
    console.log(JSON.stringify({ result: 'ok', mode: 'not-configured', checks: 11 }));
    return;
  }

  const created = await request('/api/assistant/conversations', {
    method: 'POST', token, body: { memoryEnabled: true },
  });
  assert.equal(created.status, 201);
  assert.equal(created.payload.conversation.memoryEnabled, true, 'long-term memory must require and preserve explicit consent');
  assert.equal(created.payload.messages.length, 1, 'first greeting must be generated by the server model');
  assert.equal(created.payload.messages[0].role, 'ASSISTANT');
  const conversationId = created.payload.conversation.id;

  const isolated = await request(`/api/assistant/conversations/${conversationId}/messages`, { token: bob.accessToken });
  assert.equal(isolated.status, 404, 'another account must not read the conversation');

  const messageRequestId = randomUUID();
  const question = await request(`/api/assistant/conversations/${conversationId}/messages`, {
    method: 'POST',
    token,
    body: {
      requestId: messageRequestId,
      content: '请只根据学堂现有课程解释人工智能如何学习规律，并列出来源。',
      memoryEnabled: true,
    },
  });
  assert.equal(question.status, 200);
  assert.equal(question.payload.assistantMessage.intent, 'QUESTION');
  assert.ok(question.payload.assistantMessage.sources.length > 0, 'learning answer must carry real sources');
  assert.ok(question.payload.assistantMessage.sources.every((source) => source.id && source.href));
  const memoryEnabledConversations = await request('/api/assistant/conversations', { token });
  const updatedConversation = memoryEnabledConversations.payload.find((item) => item.id === conversationId);
  assert.equal(updatedConversation.memoryEnabled, true);
  assert.equal(updatedConversation.title, question.payload.userMessage.body.slice(0, 36), 'first user message must become the conversation title');

  const duplicate = await request(`/api/assistant/conversations/${conversationId}/messages`, {
    method: 'POST',
    token,
    body: { requestId: messageRequestId, content: '这段内容不应覆盖第一次请求', memoryEnabled: true },
  });
  assert.equal(duplicate.status, 200);
  assert.equal(duplicate.payload.userMessage.id, question.payload.userMessage.id);
  assert.equal(duplicate.payload.assistantMessage.id, question.payload.assistantMessage.id);

  const feedbackId = randomUUID();
  const feedback = await request('/api/assistant/feedback', {
    method: 'POST', token,
    body: { requestId: feedbackId, messageId: question.payload.assistantMessage.id, helpful: true },
  });
  assert.equal(feedback.status, 200);
  const repeatedFeedback = await request('/api/assistant/feedback', {
    method: 'POST', token,
    body: { requestId: feedbackId, messageId: question.payload.assistantMessage.id, helpful: false },
  });
  assert.equal(repeatedFeedback.payload.id, feedback.payload.id, 'feedback requestId must be idempotent');
  assert.equal(repeatedFeedback.payload.helpful, true);

  const removedMessage = await request(`/api/assistant/conversations/${conversationId}/messages/${question.payload.assistantMessage.id}`, {
    method: 'DELETE', token,
  });
  assert.equal(removedMessage.status, 204, 'current user must delete one assistant message');
  const afterMessageDelete = await request(`/api/assistant/conversations/${conversationId}/messages`, { token });
  assert.equal(afterMessageDelete.status, 200);
  assert.ok(afterMessageDelete.payload.every((message) => message.id !== question.payload.assistantMessage.id));
  const missingMessageDelete = await request(`/api/assistant/conversations/${conversationId}/messages/${question.payload.assistantMessage.id}`, {
    method: 'DELETE', token,
  });
  assert.equal(missingMessageDelete.status, 404, 'deleting the same message twice must be rejected');

  const removed = await request(`/api/assistant/conversations/${conversationId}`, { method: 'DELETE', token });
  assert.equal(removed.status, 204);
  const missing = await request(`/api/assistant/conversations/${conversationId}/messages`, { token });
  assert.equal(missing.status, 404);

  console.log(JSON.stringify({ result: 'ok', mode: 'configured', checks: 30 }));
})().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
