const assert = require('node:assert/strict');
const { randomUUID } = require('node:crypto');

const baseUrl = String(process.env.ZHIQU_API_BASE_URL || 'http://127.0.0.1:18080').replace(/\/+$/, '');

async function request(path, { method = 'GET', token, body } = {}) {
  const headers = { Accept: 'application/json' };
  if (token) headers.Authorization = `Bearer ${token}`;
  if (body !== undefined) headers['Content-Type'] = 'application/json';
  const response = await fetch(`${baseUrl}${path}`, {
    method,
    headers,
    body: body === undefined ? undefined : JSON.stringify(body),
  });
  const text = await response.text();
  let payload = null;
  try { payload = text ? JSON.parse(text) : null; } catch { payload = text; }
  return { status: response.status, payload };
}

async function register(prefix, nickname) {
  const suffix = randomUUID().replaceAll('-', '').slice(0, 10);
  const response = await request('/api/auth/register', {
    method: 'POST',
    body: { username: `${prefix}${suffix}`, password: 'SafePass123!', nickname },
  });
  assert.equal(response.status, 201, `register ${prefix}`);
  return response.payload;
}

(async () => {
  const unauthenticated = await request('/api/assistant/config');
  assert.equal(unauthenticated.status, 401, 'assistant config must require login');
  const unauthenticatedCancel = await request(`/api/assistant/requests/${randomUUID()}`, { method: 'DELETE' });
  assert.equal(unauthenticatedCancel.status, 401, 'generation cancellation must require login');

  const alice = await register('assist', '小知');
  const bob = await register('assistb', '小问');
  const token = alice.accessToken;

  const config = await request('/api/assistant/config', { token });
  assert.equal(config.status, 200);
  assert.equal(config.payload.longTermMemoryDefault, false);
  assert.equal(config.payload.maxMessageCharacters, 2000);

  const liveRecommendations = await request('/api/assistant/recommendations', { token });
  assert.equal(liveRecommendations.status, 200);
  assert.ok(Array.isArray(liveRecommendations.payload));
  assert.ok(liveRecommendations.payload.every((item) => item.contentId && item.href === `/content/${item.contentId}`));
  const idleCancel = await request(`/api/assistant/requests/${randomUUID()}`, { method: 'DELETE', token });
  assert.equal(idleCancel.status, 204, 'cancelling a missing or completed request must be idempotent');

  if (!config.payload.configured) {
    const unavailable = await request('/api/assistant/conversations', {
      method: 'POST', token, body: { requestId: randomUUID(), memoryEnabled: false },
    });
    assert.equal(unavailable.status, 503, 'missing AI config must not return a fake greeting');
    assert.equal(unavailable.payload.code, 'AI_NOT_CONFIGURED');
    const empty = await request('/api/assistant/conversations', { token });
    assert.deepEqual(empty.payload, [], 'failed greeting must not create a conversation');
    console.log(JSON.stringify({ result: 'ok', mode: 'not-configured', checks: 13 }));
    return;
  }

  const created = await request('/api/assistant/conversations', {
    method: 'POST', token, body: { requestId: randomUUID(), memoryEnabled: true },
  });
  assert.equal(created.status, 201);
  assert.equal(created.payload.conversation.memoryEnabled, true, 'long-term memory must require and preserve explicit consent');
  assert.equal(created.payload.messages.length, 1, 'first greeting must be generated by the server model');
  assert.equal(created.payload.messages[0].role, 'ASSISTANT');
  const conversationId = created.payload.conversation.id;

  const isolated = await request(`/api/assistant/conversations/${conversationId}/messages`, { token: bob.accessToken });
  assert.equal(isolated.status, 404, 'another account must not read the conversation');

  const messageRequestId = randomUUID();
  const originalQuestionContent = '请只根据学堂现有课程解释人工智能如何学习规律，并列出来源。';
  const question = await request(`/api/assistant/conversations/${conversationId}/messages`, {
    method: 'POST',
    token,
    body: {
      requestId: messageRequestId,
      content: originalQuestionContent,
      memoryEnabled: true,
    },
  });
  assert.equal(question.status, 200);
  assert.equal(question.payload.assistantMessage.intent, 'QUESTION');
  assert.ok(question.payload.assistantMessage.sources.length > 0, 'learning answer must carry real sources');
  assert.ok(question.payload.assistantMessage.sources.every((source) => source.id && source.href));
  const memoryEnabledConversations = await request('/api/assistant/conversations', { token });
  const updatedConversation = memoryEnabledConversations.payload.find((item) => item.id === conversationId);
  assert.equal(updatedConversation.memoryEnabled, true);
  assert.equal(updatedConversation.title, question.payload.userMessage.body.slice(0, 36), 'first user message must become the conversation title');

  const duplicate = await request(`/api/assistant/conversations/${conversationId}/messages`, {
    method: 'POST',
    token,
    body: { requestId: messageRequestId, content: '这段内容不应覆盖第一次请求', memoryEnabled: true },
  });
  assert.equal(duplicate.status, 200);
  assert.equal(duplicate.payload.userMessage.id, question.payload.userMessage.id);
  assert.equal(duplicate.payload.assistantMessage.id, question.payload.assistantMessage.id);

  const editedQuestionContent = '请根据学堂里的真实课程，用三句话重新解释人工智能怎样学习规律，并保留来源。';
  const editRequestId = randomUUID();
  const edited = await request(`/api/assistant/conversations/${conversationId}/messages/${question.payload.userMessage.id}`, {
    method: 'PUT',
    token,
    body: { requestId: editRequestId, content: editedQuestionContent, memoryEnabled: true },
  });
  assert.equal(edited.status, 200, 'latest user message must be editable');
  assert.equal(edited.payload.userMessage.id, question.payload.userMessage.id, 'editing must preserve the user message ID');
  assert.equal(edited.payload.assistantMessage.id, question.payload.assistantMessage.id, 'editing must preserve the assistant message ID');
  assert.equal(edited.payload.userMessage.body, editedQuestionContent, 'editing must persist the new user content');

  const afterEdit = await request(`/api/assistant/conversations/${conversationId}/messages`, { token });
  assert.equal(afterEdit.status, 200);
  assert.equal(afterEdit.payload.filter((message) => message.id === question.payload.userMessage.id).length, 1, 'edited user message must not be duplicated');
  assert.equal(afterEdit.payload.filter((message) => message.id === question.payload.assistantMessage.id).length, 1, 'regenerated assistant reply must replace the old reply');
  assert.ok(afterEdit.payload.every((message) => message.body !== originalQuestionContent), 'the old user content must no longer be stored');

  const repeatedEdit = await request(`/api/assistant/conversations/${conversationId}/messages/${question.payload.userMessage.id}`, {
    method: 'PUT',
    token,
    body: { requestId: editRequestId, content: '重复请求不应再次改写内容', memoryEnabled: true },
  });
  assert.equal(repeatedEdit.status, 200);
  assert.equal(repeatedEdit.payload.userMessage.id, edited.payload.userMessage.id);
  assert.equal(repeatedEdit.payload.assistantMessage.id, edited.payload.assistantMessage.id);

  const regenerateRequestId = randomUUID();
  const regenerated = await request(`/api/assistant/conversations/${conversationId}/messages/${question.payload.userMessage.id}`, {
    method: 'PUT',
    token,
    body: { requestId: regenerateRequestId, content: editedQuestionContent, memoryEnabled: true },
  });
  assert.equal(regenerated.status, 200, 'regeneration must use the existing user exchange');
  assert.equal(regenerated.payload.userMessage.id, question.payload.userMessage.id, 'regeneration must not create another user message');
  assert.equal(regenerated.payload.assistantMessage.id, question.payload.assistantMessage.id, 'regeneration must replace the existing assistant reply');
  const afterRegenerate = await request(`/api/assistant/conversations/${conversationId}/messages`, { token });
  assert.equal(afterRegenerate.payload.filter((message) => message.role === 'USER').length, 1, 'regeneration must keep one user message in the exchange');
  assert.equal(afterRegenerate.payload.filter((message) => message.role === 'ASSISTANT').length, 2, 'regeneration must keep the greeting and one reply only');

  const isolatedEdit = await request(`/api/assistant/conversations/${conversationId}/messages/${question.payload.userMessage.id}`, {
    method: 'PUT',
    token: bob.accessToken,
    body: { requestId: randomUUID(), content: '另一个账号不能修改', memoryEnabled: false },
  });
  assert.equal(isolatedEdit.status, 404, 'another account must not edit the message');

  const followUp = await request(`/api/assistant/conversations/${conversationId}/messages`, {
    method: 'POST',
    token,
    body: { requestId: randomUUID(), content: '谢谢，请记住刚才的解释方式。', memoryEnabled: true },
  });
  assert.equal(followUp.status, 200);
  const nonLatestEdit = await request(`/api/assistant/conversations/${conversationId}/messages/${question.payload.userMessage.id}`, {
    method: 'PUT',
    token,
    body: { requestId: randomUUID(), content: '这条已经不是最近消息', memoryEnabled: true },
  });
  assert.equal(nonLatestEdit.status, 409, 'older user messages must not be editable');
  assert.equal(nonLatestEdit.payload.code, 'ASSISTANT_EDIT_NOT_LATEST');

  const personaActivation = await request(`/api/assistant/conversations/${conversationId}/messages`, {
    method: 'POST',
    token,
    body: { requestId: randomUUID(), content: '心爱的少女在哪里？', memoryEnabled: true },
  });
  assert.equal(personaActivation.status, 200, 'hidden persona activation must use the real message endpoint');
  assert.equal(personaActivation.payload.assistantMessage.body, '我爱你', 'activation reply must match the configured product response');
  assert.equal(personaActivation.payload.assistantMessage.intent, 'CHAT');

  const personaFollowUp = await request(`/api/assistant/conversations/${conversationId}/messages`, {
    method: 'POST',
    token,
    body: { requestId: randomUUID(), content: '你还在这里吗？', memoryEnabled: true },
  });
  assert.equal(personaFollowUp.status, 200, 'later messages must continue through the real model in the activated conversation');
  assert.ok(personaFollowUp.payload.assistantMessage.body.trim().length > 0);

  const feedbackId = randomUUID();
  const feedback = await request('/api/assistant/feedback', {
    method: 'POST', token,
    body: { requestId: feedbackId, messageId: question.payload.assistantMessage.id, helpful: true },
  });
  assert.equal(feedback.status, 200);
  const repeatedFeedback = await request('/api/assistant/feedback', {
    method: 'POST', token,
    body: { requestId: feedbackId, messageId: question.payload.assistantMessage.id, helpful: false },
  });
  assert.equal(repeatedFeedback.payload.id, feedback.payload.id, 'feedback requestId must be idempotent');
  assert.equal(repeatedFeedback.payload.helpful, true);

  const removedMessage = await request(`/api/assistant/conversations/${conversationId}/messages/${question.payload.assistantMessage.id}`, {
    method: 'DELETE', token,
  });
  assert.equal(removedMessage.status, 204, 'current user must delete one assistant message');
  const afterMessageDelete = await request(`/api/assistant/conversations/${conversationId}/messages`, { token });
  assert.equal(afterMessageDelete.status, 200);
  assert.ok(afterMessageDelete.payload.every((message) => message.id !== question.payload.assistantMessage.id));
  const missingMessageDelete = await request(`/api/assistant/conversations/${conversationId}/messages/${question.payload.assistantMessage.id}`, {
    method: 'DELETE', token,
  });
  assert.equal(missingMessageDelete.status, 404, 'deleting the same message twice must be rejected');

  const removed = await request(`/api/assistant/conversations/${conversationId}`, { method: 'DELETE', token });
  assert.equal(removed.status, 204);
  const missing = await request(`/api/assistant/conversations/${conversationId}/messages`, { token });
  assert.equal(missing.status, 404);

  console.log(JSON.stringify({ result: 'ok', mode: 'configured', checks: 58 }));
})().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
