const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const vm = require('node:vm');

const frontendRoot = path.join(__dirname, '..');
const dist = path.join(frontendRoot, 'dist');
const script = fs.readFileSync(path.join(dist, 'magic-room-reference.js'), 'utf8');
const lobbyScript = fs.readFileSync(path.join(dist, 'magic-reference.js'), 'utf8');
const css = fs.readFileSync(path.join(dist, 'magic-room-reference.css'), 'utf8');
const server = fs.readFileSync(path.join(frontendRoot, 'serve-static.cjs'), 'utf8');
const assetRoot = path.join(dist, 'assets', 'figma-magic-room', 'runtime');

assert.doesNotThrow(() => new vm.Script(script, { filename: 'magic-room-reference.js' }), 'magic room script must parse');
assert.match(css, /aspect-ratio:\s*852\s*\/\s*393/, 'room stage must preserve the landscape Figma frame ratio');
assert.match(css, /@media\s*\(orientation:\s*portrait\)\s*\{[\s\S]*body\[data-zq-magic-landscape\]\s+\.magic-room-stage\s*\{[^}]*width:\s*min\(100vh,\s*calc\(100vw\s*\*\s*2\.16794\)\);[^}]*height:\s*min\(100vw,\s*calc\(100vh\s*\/\s*2\.16794\)\);/s, 'portrait rotation must size the room stage from the swapped viewport axes');
assert.match(css, /\.magic-room-background\s*\{[^}]*background:\s*url\([^)]*figma-115-meadow-background\.png[^}]*\/\s*cover\s+no-repeat;/s, 'room background must use the exported Figma meadow artwork and cover the full stage');
assert.match(css, /\.magic-room-publish-band\s*\{[^}]*top:\s*27\.2%;[^}]*left:\s*14%;[^}]*width:\s*71\.5%;/s, 'publish band must retain the Figma 114 geometry');
assert.match(css, /\.magic-room-invite-card\s*\{[^}]*top:\s*46\.2%;[^}]*left:\s*22\.5%;[^}]*width:\s*49\.8%;/s, 'invite card must retain the Figma 114 geometry');
assert.match(css, /\.magic-room-player--mentor\s*\{\s*left:\s*28%;/s, 'mentor badge must align with the Figma 114 header');
assert.match(css, /\.magic-room-player--novice\s*\{\s*left:\s*54\.2%;/s, 'novice badge must align with the Figma 114 header');
assert.match(script, /api\(`\/api\/magic-game-rooms\/\$\{encodeURIComponent\(id\)\}`\)/, 'room data must come from the real magic room endpoint');
assert.doesNotMatch(script, /room\?\.status\s*!==\s*'LOBBY'[\s\S]*removeShell\(\)/, 'active gameplay must never reveal the rotated legacy page');
assert.match(script, /case 'LOBBY':[\s\S]*case 'ROUND_1':[\s\S]*case 'ROUND_2':[\s\S]*case 'RESULT':/, 'the landscape shell must render every room stage');
assert.match(script, /room\?\.mentor\?\.nickname/, 'mentor nickname must come from the room snapshot');
assert.match(script, /room\?\.novice\?\.nickname/, 'novice nickname must come from the room snapshot');
assert.match(script, /mentor\?\.avatarKey/, 'mentor account avatar must come from the room snapshot');
assert.match(script, /novice\?\.avatarKey/, 'novice account avatar must come from the room snapshot');
assert.match(script, /api\/social\/avatars/, 'uploaded account avatars must use the existing protected media route');
assert.match(script, /data-room-account-avatar-image/, 'avatar image failures must have a DOM fallback hook');
assert.match(script, /magic-room-player-nameplate has-star[\s\S]*asset-25\.png[\s\S]*magic-room-player-star/, 'mentor nickname must use the Figma nameplate and star treatment');
assert.match(script, /magic-room-player-nameplate[\s\S]*asset-25\.png[\s\S]*data-room-novice-name/, 'novice waiting state must use the Figma nameplate');
assert.match(css, /\.magic-room-player-nameplate\s*\{[^}]*left:\s*-18%;[^}]*width:\s*136%;[^}]*height:\s*24%;/s, 'both player nameplates must be large enough for readable account names');
assert.match(css, /\.magic-room-player-name\s*\{[^}]*font-size:\s*clamp\(9px,\s*1\.28cqw,\s*13px\);/s, 'player names must scale with the enlarged nameplates');
assert.match(css, /\.magic-room-player--mentor \.magic-room-player-role\s*\{[^}]*color:\s*#fffaf1;/, 'mentor ribbon label must use the light Figma treatment');
assert.match(css, /\.magic-room-publish-icon\s*\{[^}]*top:\s*50%;[^}]*left:\s*7\.3%;[^}]*transform:\s*translate\(-50%,\s*-50%\);/, 'the brown globe badge must use its circle center as the positioning anchor');
assert.match(css, /\.magic-room-globe-brown\s*\{[^}]*inset:\s*0;[^}]*width:\s*70%;[^}]*height:\s*70%;[^}]*margin:\s*auto;/, 'the brown globe must be centered within the badge on both axes');
assert.doesNotMatch(css.match(/\.magic-room-globe-brown\s*\{[^}]*\}/)?.[0] || '', /transform:\s*translateY\(/, 'the brown globe must not use an off-center vertical offset');
assert.match(css, /\.magic-room-globe-white\s*\{[^}]*top:\s*50%;[^}]*left:\s*20\.5%;[^}]*translate\(-50%,\s*-50%\)\s*translate\(10%,\s*10%\);/, 'the white globe must compensate for the source asset transparent padding');
assert.match(script, /magic-room-publish-band\$\{listing \? ' is-public' : ''\}\$\{publishAnimation/, 'the publish card must expose distinct active and completed visual states');
assert.match(script, /发布中\.\.\./, 'publishing must provide immediate text feedback');
assert.match(script, /撤下中\.\.\./, 'unpublishing must provide immediate text feedback');
assert.match(css, /@keyframes\s+magic-room-publish-wave/, 'publishing must animate a globe wave');
assert.match(css, /@keyframes\s+magic-room-publish-shine/, 'publishing must animate a card highlight');
assert.match(css, /@keyframes\s+magic-room-unpublish-wave/, 'unpublishing must animate a contracting globe wave');
assert.match(css, /@keyframes\s+magic-room-unpublish-shine/, 'unpublishing must animate a reverse card highlight');
assert.match(script, /room\?\.inviteCode/, 'invite code must come from the room snapshot');
assert.doesNotMatch(script, /123456|小画家/, 'runtime room data must not be hard-coded');
assert.match(script, /\/api\/community\/game-listings\/mine/, 'published state must come from the real listing endpoint');
assert.match(script, /gameCode:\s*'MAGIC',\s*roomId:\s*currentRoom\.id/, 'publish must use the real room id');
assert.match(script, /game-listings\/\$\{encodeURIComponent\(currentListing\.id\)\}\/close/, 'unpublish must close the real listing');
assert.match(script, /method:\s*'DELETE'/, 'cancel must use the real room delete action');
assert.doesNotMatch(script, /globalThis\.confirm|window\.confirm/, 'cancel must not depend on a browser-native confirm dialog');
assert.match(script, /data-room-dialog/, 'exit must use an in-page confirmation dialog');
assert.match(script, /if \(event\.target\.closest\('\[data-room-exit\]'\)\) handleExitRequest\(\)/, 'the first exit click must only open the confirmation dialog');
assert.match(script, /if \(event\.target\.closest\('\[data-room-dialog-confirm\]'\)\) await confirmExit\(\)/, 'only the explicit confirmation action may end or leave the room');
assert.match(script, /if \(event\.target\.closest\('\[data-room-dialog-dismiss\]'\)\) closeDialog\(\)/, 'the confirmation dialog must let players continue the game');
assert.match(css, /\.magic-room-cancel-dialog\[hidden\]\s*\{\s*display:\s*none;/, 'the in-page confirmation dialog must be hidden until requested');
assert.match(script, /error\.status\s*=\s*response\.status/, 'API errors must retain their HTTP status');
assert.match(script, /roomIsUnavailable\(error\)[\s\S]*navigateAfterExit\(\)/, 'stale or unauthorized room pages must return to the lobby');
assert.match(script, /const navigate = \(path\) => \{[\s\S]*exitInProgress\s*=\s*true;[\s\S]*clearInterval\(roomTimer\)[\s\S]*location\.replace\(path\)/, 'navigation must freeze the current room artwork until the next document takes over');
assert.match(script, /createShell\(\);\s*refreshRoom\(\)/, 'room artwork must mount before the first room request finishes');
assert.match(script, /__zqMagicEntryTransitionRuntimeV2\?\.complete\?\.\(\)/, 'the landscape room shell must actively release the entry cover after mounting');
assert.match(script, /roomReady\s*=\s*room\?\.id && room\?\.status \? 'true' : 'false'/, 'the room shell must wait for a real room snapshot before releasing the cover');
assert.match(script, /mentor-cast-async[\s\S]*novice-cast/, 'both term casting endpoints must be implemented by the landscape UI');
assert.match(script, /endpoint === 'mentor-cast-async'/, 'creator generation must use the non-blocking server endpoint');
assert.match(script, /body:\s*JSON\.stringify\(\{ requestId:\s*requestId\(\), terms:\s*selectedTerms \}\)/, 'term casting must preserve the real request contract');
assert.match(script, /room\?\.mentorImageUrl/, 'the generated challenge image must render from the room response');
assert.match(script, /GENERATION_LAUNCH_MS\s*=\s*360/, 'generation must reserve a short visible launch effect before changing screens');
assert.match(script, /classList\.add\('is-launching'\)[\s\S]*setTimeout\(resolve, GENERATION_LAUNCH_MS\)/, 'the generation button must play its launch effect before entering the waiting board');
assert.match(css, /\.magic-room-figma-generate\.is-launching\s*\{[^}]*magic-room-generate-launch/, 'the generation action must have a dedicated click animation');
assert.match(css, /@keyframes\s+magic-room-generate-launch-ripple/, 'the generation click must emit a visible confirmation ripple');
assert.match(script, /image-progress/, 'generation progress must be queried from the room progress endpoint');
assert.match(script, /setInterval\(pollGenerationProgress,\s*900\)/, 'generation stage progress must refresh while the provider is working');
assert.match(script, /--generation-progress:\$\{progress\.progress\}%/, 'the progress bar width must use the reported generation percentage');
assert.match(css, /\.magic-room-generating-progress i\s*\{[^}]*width:\s*var\(--generation-progress,\s*8%\)/, 'the progress fill must be driven by the runtime percentage');
assert.match(script, /addEventListener\('load',[\s\S]*completeGeneratedImageLoad/, '100 percent must wait for the generated image load event');
assert.match(script, /status:\s*'READY',[\s\S]*progress:\s*100/, 'the loaded generated image must finish the progress bar at 100 percent');
assert.match(script, /payload\?\.status === 'FAILED'[\s\S]*clearGenerationProgress\(\)/, 'a failed provider stage must stop progress and return the creator to a retry state');
assert.match(script, /magic-room-vs-role">先手创作者/, 'the creator role must render in a dedicated identity label');
assert.match(script, /magic-room-vs-role">猜图者/, 'the guesser role must render in a dedicated identity label');
assert.match(script, /const creatorIsGenerating = room\.currentUserRole === 'MENTOR'[\s\S]*const guesserIsWaiting = room\.currentUserRole === 'NOVICE'[\s\S]*if \(creatorIsGenerating \|\| guesserIsWaiting\) startGenerationProgress/, 'generation waiting must respect the current account role');
assert.match(script, /renderRoundOne[\s\S]*return renderCreatorBoard\(room\)/, 'a creator who has not started generation must see the term selection board');
assert.match(script, /renderCreatorGeneratingBoard/, 'creator generation board must be separate');
assert.match(script, /renderGuesserWaitingBoard/, 'guesser waiting board must be separate');
assert.match(script, /renderCreatorWaitingBoard/, 'creator answer waiting board must be separate');
assert.match(css, /\.magic-room-generating-dots\s*\{[^}]*margin-top:\s*2\.9cqw;[^}]*gap:\s*\.72cqw;/, 'generation dots must share the waiting indicator baseline spacing');
assert.match(css, /\.magic-room-generating-dots i\s*\{[^}]*width:\s*1\.05cqw;[^}]*animation:\s*magic-room-dot 1\.45s ease-in-out infinite;/, 'generation dots must match the waiting indicator size and timing');
assert.match(script, /你的挑战图正在生成/, 'creator must see creator-specific generation text');
assert.match(script, /等待创作者完成挑战图/, 'guesser must see guesser-specific waiting text');
assert.match(script, /renderRoundOne[\s\S]*renderCreatorGeneratingBoard[\s\S]*renderGuesserWaitingBoard/, 'round one must branch by role');
assert.match(script, /magic-room-guesser-waiting-game/, 'guesser waiting state must expose a dedicated class');
assert.match(css, /\.magic-room-guesser-waiting-game \.magic-room-generating-card/, 'guesser waiting state must have distinct styling');
assert.match(css, /\.magic-room-creator-generating-game \.magic-room-generating-card/, 'creator generation state must have distinct styling');
assert.match(script, /let boundRoomSession = null[\s\S]*const roomSession = \(\) => boundRoomSession \|\| session\(\)/, 'each room tab must bind its own login session');
assert.match(script, /const token = roomSession\(\)\?\.accessToken/, 'room polling must not switch accounts when another tab logs in');
assert.match(script, /trackedRoomId !== id[\s\S]*boundRoomSession = session\(\)/, 'room session must be captured when entering a new room');
assert.match(script, /response\.status === 401[\s\S]*refreshRoomSession\(\)/, 'an expired bound room token must refresh without reading another tab account');
assert.match(script, /roomUnavailableAttempts\s*\+=\s*1[\s\S]*generationStillRunning[\s\S]*roomUnavailableAttempts\s*<\s*4/, 'generation must tolerate transient room responses before leaving');
assert.match(css, /\.magic-room-vs-role\s*\{(?=[^}]*background:\s*rgba\(255,\s*250,\s*229,\s*\.94\);)(?=[^}]*border-radius:\s*999px;)[^}]*\}/s, 'role labels must have a high-contrast backing against the meadow');
assert.match(css, /\.magic-room-vs-player--novice \.magic-room-vs-role\s*\{[^}]*color:\s*#704187;/s, 'the guesser role label must retain its distinct purple treatment');
assert.match(script, /bindPictureLoadErrors\(\)/, 'generated image load failures must show a visible fallback instead of a blank frame');
for (const term of [
  '海边灯塔', '雪山小屋', '城市天台', '热带雨林',
  '一只橘猫', '一个小机器人', '一位穿黄色雨衣的孩子', '一只白色风筝',
  '清晨薄雾', '金色夕阳', '雨后彩虹', '蓝色月夜',
  '童话水彩', '彩色蜡笔', '立体纸雕', '黏土定格',
]) assert.match(script, new RegExp(term), `frontend must include the approved term ${term}`);
assert.match(script, /selectedTermsAreValid\(\)/, 'the UI must reject stale or cross-category terms before sending them');
assert.match(script, /room\?\.noviceImageUrl/, 'the result comparison image must render from the room response');
assert.match(script, /magic-room-result-answer/, 'a completed guess without a second image must render a clear answer summary');
assert.doesNotMatch(script, /提示卡/, 'guessing must not advertise an unimplemented hint-card feature');
assert.doesNotMatch(script, /剩余时间：01:58/, 'guessing must not ship a fixed countdown label');
assert.match(script, /GUESS_DURATION_MS\s*=\s*2\s*\*\s*60\s*\*\s*1_000/, 'guessing must define a real two-minute round duration');
assert.match(script, /setInterval\(updateCountdown,\s*1_000\)/, 'the guessing countdown must update every second');
assert.match(script, /sessionStorage\?\.setItem\(key,\s*String\(deadline\)\)/, 'the round deadline must survive message polling and page rerenders');
assert.match(script, /remaining\s*>\s*0[\s\S]*submitTerms\(\)\.finally/, 'time expiry must submit through the real novice-cast flow');
assert.match(script, /时间到，正在进入结算/, 'the zero timer state must explicitly advance to the result flow');
assert.match(script, /时间到，正在重试结算/, 'a transient submit failure must retry the completion flow instead of remaining permanently stuck');
assert.match(script, /timeoutMs:\s*12_000/, 'a guess submission must recover from a stalled network request instead of remaining in submitting state');
assert.match(script, /controller\?\.signal\.aborted[\s\S]*提交响应超时，正在重新同步结算结果/, 'a timed-out submission must show a recoverable result-sync state');
assert.match(script, /currentRoom\?\.mentorImageUrl/, 'the countdown must wait for a generated challenge image');
assert.match(script, /challengeReady/, 'a room without a generated image must block answer submission instead of showing a blank game');
assert.match(script, /data-room-refresh/, 'room load failures must provide an in-page reconnect action');
assert.match(script, /__zqMagicRoomReferenceRuntimeV4/, 'a repeat route transition must dispose the previous room runtime');
assert.match(script, /runtime\.ensure\s*=\s*boot/, 'the active room overlay must expose a route recheck hook');
assert.match(script, /room\?\.matchScore/, 'the result score must render from the room response');
assert.match(script, /\/swap/, 'role swapping must use the real room endpoint');
assert.match(script, /\/leave/, 'a novice must be able to leave without deleting the room directly');
assert.doesNotMatch(script, /这局运用到了什么知识/, 'the review page must not retain the detached knowledge heading');
assert.match(script, /magic-room-record-review/, 'review content must share one bounded mobile layout container');
assert.match(css, /\.magic-room-review-content\s*\{[^}]*display:\s*grid;[^}]*grid-template-columns:\s*\.95fr\s+1\.18fr\s+\.87fr;/s, 'review cards must use a non-overlapping landscape grid');
assert.match(css, /\.magic-room-review-card h2\s*\{[^}]*margin:\s*0\s+0\s+1\.05cqw;/s, 'review headings must retain visible spacing from their content');
assert.match(css, /\.magic-room-review-actions\s*\{[^}]*display:\s*grid;[^}]*grid-template-columns:\s*minmax\(0,\s*1fr\)\s+minmax\(0,\s*1\.25fr\);/s, 'review navigation actions must occupy separate fixed grid tracks');
assert.doesNotMatch(css, /\.magic-room-review-course button\s*\{[^}]*position:\s*absolute;/s, 'the learn button must remain inside its course card flow');
assert.match(css, /\.magic-room-game-area\s*\{[^}]*top:\s*24%;[^}]*height:\s*72\.8%;/s, 'active gameplay must fit below the landscape header');
assert.match(css, /\.magic-room-status span\s*\{[^}]*inset:\s*0\s+5%\s+0\s+31%;[^}]*display:\s*grid;[^}]*place-items:\s*center;[^}]*text-align:\s*center;/s, 'the room status copy must be centered in the plaque area beside its icon');
assert.match(css, /\.magic-room-ended-layer\s*\{[^}]*position:\s*absolute;[^}]*inset:\s*0;[^}]*display:\s*grid;[^}]*width:\s*100%;[^}]*height:\s*100%;[^}]*place-items:\s*center;/s, 'the ended challenge layer must center against the complete landscape stage');
assert.match(script, /<main class="magic-room-ended-layer is-finished">/, 'finished rooms must mark their card separately from the initial loading card');
assert.match(css, /\.magic-room-ended-layer\.is-finished \.magic-room-ended-card\s*\{[^}]*transform:\s*translateX\(-2cqw\);/s, 'the rotated finished card must keep equal visible top and bottom margins');
assert.match(css, /\.magic-room-ended-card\s*\{[^}]*position:\s*relative;[^}]*width:\s*min\(58%,\s*520px\);[^}]*height:\s*min\(64%,\s*250px\);[^}]*margin:\s*0;/s, 'the ended challenge panel must use a responsive bounded card size');
assert.match(css, /\.magic-room-ended-card\s*>\s*span\s*\{[^}]*width:\s*clamp\(52px,\s*8cqw,\s*78px\);/s, 'the ended challenge icon must scale with the card instead of the tiny legacy size');
assert.match(css, /\.magic-room-ended-card h1\s*\{[^}]*font-size:\s*clamp\(20px,\s*3\.1cqw,\s*32px\);/s, 'the ended challenge title must remain readable at mobile scale');
assert.match(css, /\.magic-room-ended-card\s*\{[^}]*border-color:\s*#c79549;[^}]*background:\s*#fffbe9;/s, 'the ended challenge panel must use an opaque border and fill on every edge');
assert.match(css, /\.magic-room-ended-card\s*\{[^}]*box-shadow:\s*0\s+0\s+0\s+\.1cqw\s+rgba\([^)]*\),\s*0\s+0\s+1\.15cqw\s+rgba\([^)]*\);/s, 'the ended challenge panel shadow must have no directional offset');
assert.doesNotMatch(script, /class="magic-room-game-area magic-room-ended-card"/, 'the ended card must not inherit the offset gameplay content area');
assert.match(css, /\.magic-room-guess-layout\s*\{\s*grid-template-columns:\s*38\.5%\s+minmax\(0,\s*1fr\);/, 'guessing must use a landscape image-and-controls split');
assert.match(css, /\.magic-room-guess-row\s*>\s*div\s*\{[^}]*grid-template-columns:\s*repeat\(4,\s*minmax\(0,\s*1fr\)\);/s, 'all four choices in each guessing category must share one row instead of overflowing the board');
assert.match(css, /\.magic-room-guess-row\s+\.magic-room-figma-term\s*\{[^}]*overflow-wrap:\s*anywhere;[^}]*white-space:\s*normal;/s, 'long guessing choices must wrap inside their buttons without overlapping adjacent content');
assert.match(css, /\.magic-room-guess-board\s*\{[^}]*height:\s*65%;[^}]*grid-template-columns:\s*44%\s+minmax\(0,\s*1fr\);/s, 'the guessing board must reserve enough room for the full image and every choice row');
assert.match(css, /\.magic-room-guess-image\s+\.magic-room-generated-image\s*\{[^}]*object-fit:\s*contain;/s, 'the challenge image must show in full instead of being cropped');
assert.match(css, /\.magic-room-guess-options\s*\{[^}]*grid-template-rows:\s*repeat\(4,\s*minmax\(0,\s*1fr\)\);/s, 'all four prompt categories must receive an equal visible row');
assert.match(css, /\.magic-room-guess-actions\s*\{[^}]*grid-template-columns:\s*1\.55fr\s+1fr;/s, 'guessing actions must contain only the countdown and submit button');
assert.match(css, /\.magic-room-figma-term-card h2\s*\{[^}]*background:\s*#317a74;[^}]*color:\s*#fffdf4;/s, 'category headings must be visually distinct from yellow term choices');
assert.doesNotMatch(css, /\.magic-room-figma-term-card h2\s*\{[^}]*background-color:\s*#765039;/s, 'a legacy background-color must not override the category header treatment');
assert.match(css, /\.magic-room-generation-error\s*\{/, 'a failed image generation must receive an inline recovery state');
assert.match(css, /\.magic-room-generation-error\s*\{[^}]*right:\s*20%;[^}]*bottom:\s*9\.2%;[^}]*left:\s*20%;/s, 'the generation recovery card must reserve space above the action button');
assert.match(script, /data-room-submit-terms[\s\S]*重新生成挑战图/, 'a failed creator generation must provide a retry action');
assert.match(script, /actionError/, 'generation errors must survive the immediate board rerender');
assert.match(script, /creatorGenerationFailure[\s\S]*node\.hidden\s*=\s*!actionError \|\| creatorGenerationFailure/, 'creator generation failures must not duplicate the global room error bar');
assert.match(script, /syncGenerationProgress\(room\);\s*syncErrorDisplay\(\);/, 'every room rerender must resynchronize the global error bar with the inline generation failure');
assert.doesNotMatch(script, /setError\(''\);\s*createShell\(\);\s*updateShell\(room, listing\);\s*globalThis\.__zqMagicEntryTransitionRuntimeV2/s, 'background polling must not clear a recoverable generation error');
assert.match(css, /\.magic-room-account-avatar\s*\{[^}]*border-radius:\s*50%;/s, 'room account avatars must retain a round avatar crop');
assert.match(css, /\.magic-room-result-layout\s*\{\s*grid-template-columns:[^;}]*24%;/, 'results must fit both images and the score side by side');
assert.match(script, /firstReadyRender[\s\S]*is-room-entering[\s\S]*680/, 'the real first room snapshot must trigger one bounded entrance sequence');
assert.match(css, /is-room-entering[\s\S]*magic-room-enter-topbar[\s\S]*magic-room-enter-band[\s\S]*magic-room-enter-content/, 'waiting-room regions must reveal in a coordinated landscape sequence');
assert.match(server, /figma-115-meadow-background\.png/, 'the static server must prepaint the updated Figma room background');
assert.match(server, /magic-room-reference\.js/, 'the static server must inject the room overlay');
assert.match(lobbyScript, /data-zq-magic-room-reference-loader/, 'SPA navigation must inject a fresh room overlay even when a stale legacy script tag remains');
assert.match(lobbyScript, /currentRuntime\.ensure\?\.\(\)/, 'SPA navigation must immediately recheck the active room overlay');
assert.match(server, /magicRoutePrepaintHead/, 'magic routes must prepaint their forest artwork before application hydration');
assert.match(server, /zq-magic-route-prepaint/, 'magic route prepaint must cover the legacy loading screen');
assert.doesNotMatch(server, /data-zq-magic-active-stage|zhiqu\.magic\.active-stage\./, 'stale active-stage markers must not expose the legacy purple room during reload');
assert.match(server, /#root > \* \{ visibility: hidden !important; \}/, 'room prepaint must hide the legacy application until the landscape shell mounts');
assert.match(server, /body\[data-zq-magic-landscape\] #root \{[^}]*width:\s*100vh;[^}]*height:\s*100vw;/s, 'portrait devices must swap root dimensions before the 90 degree rotation');
assert.match(script, /const lockRoomLandscape = \(\) =>/, 'the room overlay must request landscape mode when injected during SPA navigation');
assert.match(script, /const isReviewRoute = \(\) =>/, 'the room overlay must distinguish a read-only review route from active play');
assert.match(script, /data-zq-magic-review/, 'the room overlay must expose a review marker for the upright summary layout');
assert.match(script, /const unlockRoomLandscape = \(\) =>/, 'the review route must release a previous gameplay orientation lock');
assert.match(script, /document\.body\?\.setAttribute\('data-zq-magic-landscape', ''\)/, 'the room overlay must set the landscape marker before its first request');
assert.match(script, /document\.body\?\.removeAttribute\('data-zq-magic-landscape'\)/, 'leaving a room route must release the room landscape marker');
assert.match(css, /body\[data-zq-magic-room-reference\] #root \{[^}]*width:\s*100vh;[^}]*height:\s*100vw;[^}]*rotate\(90deg\)/s, 'the room marker must provide an immediate portrait-to-landscape fallback');
assert.doesNotMatch(script, /figma\.com\/api\/mcp\/asset/, 'temporary Figma URLs must not ship in runtime code');

for (const name of [
  'figma-115-meadow-background.png', 'asset-01.png', 'asset-02.png', 'asset-03.png', 'asset-10.png',
  'asset-11.png', 'asset-12.png', 'asset-13.png',
  'asset-14.png', 'asset-16.png', 'asset-18.png', 'asset-19.png', 'asset-20.png', 'asset-25.png',
  'asset-26.png', 'asset-32.png', 'asset-37.png',
]) {
  const stat = fs.statSync(path.join(assetRoot, name));
  assert.ok(stat.size > (name === 'figma-115-meadow-background.png' ? 1_000_000 : 10_000), `${name} must contain a committed Figma asset`);
  assert.ok(script.includes(name) || css.includes(name), `${name} must be referenced by the room UI`);
}

assert.equal((script.match(/asset-26\.png', 'magic-room-ribbon-art'/g) || []).length, 2, 'both roles must use the same red ribbon treatment');
assert.doesNotMatch(script, /asset-33\.png', 'magic-room-ribbon-art'/, 'the novice role must not fall back to the smaller wood ribbon');

console.log('Figma magic room landscape: ok');
