const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');

const script = fs.readFileSync(path.join(__dirname, '..', 'dist', 'zhiqu-ai-assistant.js'), 'utf8');
const server = fs.readFileSync(path.join(__dirname, '..', 'serve-static.cjs'), 'utf8');
const standalonePage = fs.readFileSync(path.join(__dirname, '..', 'dist', 'ai-assistant.html'), 'utf8');

assert.match(script, /if \(window\.__zhiquAiAssistantLoaded\) return;/, 'script must mount once');
assert.match(script, /data-zq-ai-assistant-page/, 'page needs a unique mount marker');
assert.match(script, /data-zq-ai-global-nav/, 'navigation needs a unique mount marker');

const labels = ["\\u9996\\u9875", "\\u5b66\\u4e60", "AI\\u52a9\\u624b", "\\u793e\\u533a", "\\u6211\\u7684"];
let previous = -1;
for (const label of labels) {
  const position = script.indexOf("label: '" + label + "'");
  assert.ok(position > previous, `navigation item ${label} must appear in the required order`);
  previous = position;
}
assert.match(script, /href: '\/ai-assistant'/, 'assistant route must be /ai-assistant');
assert.match(script, /window\.history\.pushState\(\{\}, '', href\)/, 'top-level navigation should use in-app history transitions');
assert.doesNotMatch(script, /new PopStateEvent\('popstate'\)/, 'assistant navigation must not synthesize an Expo tab transition');
assert.doesNotMatch(script, /if \(pathName\(\) !== href\) window\.location\.assign\(href\)/, 'top-level navigation must not hard reload the full bundle');
assert.match(script, /if \(href !== '\/ai-assistant'\) \{[^}]*window\.location\.assign\(href\)/s, 'standalone assistant navigation should retain a static fallback');
assert.match(script, /function activateOriginalNav/, 'existing top-level navigation handlers should be reused');
assert.match(script, /if \(activateOriginalNav\(item\.label, function \(\) \{/, 'non-assistant tabs should delegate to the native router');
assert.match(script, /state\.nativeRoute === item\.href && pathName\(\) === '\/ai-assistant'/, 'returning to the native page underneath the assistant should use browser history');
assert.match(script, /window\.history\.back\(\)/, 'assistant-to-underlying-tab navigation should use the native history entry');
assert.match(script, /function detachAssistantOverlay/, 'assistant overlay should be removed before a native tab transition');
assert.match(script, /state\.leavingAssistant && isAssistantRoute\(\)/, 'route synchronization should not remount the assistant during its native transition');
assert.match(script, /translateY\(-8px\)/, 'active assistant icon must rise 8px');
assert.match(script, /\.zq-ai-page\{[^}]*animation:none\}/, 'assistant page should not animate when entered from another page');
assert.match(script, /@keyframes zqAiPageEnter/, 'assistant page enter keyframes must exist');
assert.match(script, /function replayNativePageEnter/, 'returning to the native page underneath the assistant should replay the native scene transition');
assert.match(script, /#root\.zq-ai-native-page-enter/, 'the native shell replay should use the same page transition');
assert.match(script, /perspective\(1400px\) rotateY\(-96deg\) scale\(\.985\)/, 'assistant page should reuse the existing tabs enter rotation, scale and perspective');
assert.doesNotMatch(script, /zqAiPageFade|zqAiPageFlip/, 'assistant page must not use a separate page transition');
assert.doesNotMatch(script, /translateX\(24px\)/, 'assistant page must not invent a separate slide transition');
assert.match(script, /\.zq-ai-nav-item\[data-active="true"\] \.zq-ai-nav-icon\{width:44px;height:44px/, 'every active navigation icon must share the assistant scale effect');
assert.match(script, /\.zq-ai-nav-item:not\(\[data-active="true"\]\):hover \.zq-ai-nav-icon/, 'every inactive navigation icon must share the hover lift effect');
assert.match(script, /createAssistantNavIcon/, 'assistant navigation must use the Lucide Sparkles fallback icon');
assert.match(script, /M11\.017 2\.814a1 1 0 0 1 1\.966 0/, 'assistant icon must use the bundled Lucide Sparkles path');
assert.match(script, /messages-square/, 'community navigation must use the MessagesSquare icon');
assert.match(script, /M16 10a2 2 0 0 1-2 2H6\.828/, 'community navigation must use the native MessagesSquare path');
assert.match(script, /user-round/, 'profile navigation must use the UserRound icon');
assert.match(script, /M20 21a8 8 0 0 0-16 0/, 'profile navigation must use the native UserRound path');
assert.match(script, /@media\(prefers-reduced-motion:reduce\)/, 'reduced motion must be supported');
assert.match(script, /min-height:52px/, 'navigation target must be at least 48px');
assert.match(script, /height:66px/, 'navigation should retain the original compact bar height');
assert.match(script, /border-radius:24px/, 'navigation should retain the original floating-bar radius');
assert.match(script, /rgba\(255,253,250,\.76\)/, 'navigation should retain the original translucent surface');
assert.match(script, /\.zq-ai-shell\{[^}]*padding-bottom:var\(--zq-ai-nav-height\)/, 'content must reserve navigation space while the page background covers the viewport');

assert.doesNotMatch(script, /QuickPromptList|presetQuestions|quickReplies/, 'preset prompt components are forbidden');
assert.doesNotMatch(script, /\u5efa\u8bae\u95ee|\u8bd5\u8bd5\u95ee|\u5feb\u6377\u56de\u590d/, 'preset question copy is forbidden');
assert.match(script, /\/api\/assistant\/config/, 'config endpoint must be used');
assert.match(script, /\/api\/assistant\/conversations/, 'conversation endpoint must be used');
assert.match(script, /\/api\/assistant\/feedback/, 'feedback endpoint must be used');
assert.match(script, /function refreshSession\(currentSession\)/, 'assistant API requests must refresh expired access tokens');
assert.match(script, /response\.status === 401 && retryAfterRefresh !== false/, 'assistant API requests must retry once after a 401');
assert.match(script, /state\.deletingId = id/, 'conversation deletion must expose an in-flight state');
assert.match(script, /deleteButton\.disabled = !!state\.deletingId/, 'conversation deletion must prevent duplicate clicks');
assert.match(script, /deleteButton\.textContent = deleting \? '\\u5220\\u9664\\u4e2d\\u2026'/, 'conversation deletion must show progress feedback');
assert.match(script, /state\.authRequired = isAuthError\(error\)/, 'expired authentication must be distinguishable from other delete failures');
assert.match(script, /className = 'zq-ai-error-action'/, 'expired authentication must offer a re-login action');
assert.match(script, /function beginConversationTransition\(\)/, 'new conversations must expose a transition state');
assert.match(script, /zqAiConversationSwitch/, 'new conversations must provide a visible switch animation');
assert.match(script, /state\.loadingLabel = animate \? '\\u6b63\\u5728\\u521b\\u5efa\\u65b0\\u5bf9\\u8bdd' : ''/, 'new conversations must explain the transition while being created');
assert.match(script, /function titleFromFirstMessage\(message\)/, 'conversation titles must derive from the first user message');
assert.match(script, /if \(firstUserMessage\) applyFirstMessageTitle\(userMessage\)/, 'first-message titles must update the sidebar after sending');
assert.match(script, /state\.draft = ''/, 'draft should clear after the message is placed into the chat');
assert.match(script, /AbortController/, 'stop generation must abort the active request');
assert.match(script, /var optimisticMessage = retryMessage \|\| \{/, 'sent text must enter the chat before generation starts');
assert.match(script, /state\.messages\.push\(optimisticMessage\)/, 'sent text must render as an immediate user message');
assert.match(script, /state\.latestMessageId = optimisticMessage\.id/, 'new user messages must receive a one-time animation marker');
assert.match(script, /data-entering/, 'new chat bubbles must expose an animation state');
assert.match(script, /@keyframes zqAiMessageIn/, 'chat bubbles must animate into the conversation');
assert.match(script, /zqAiMessageIn 560ms ease-out/, 'chat bubble animation must remain readable');
assert.match(script, /scale\(\.82\)/, 'chat bubbles must visibly grow from a smaller size');
assert.match(script, /transform-origin:bottom right/, 'user chat bubbles must grow from their lower corner');
assert.match(script, /transform-origin:bottom left/, 'assistant chat bubbles must grow from their lower corner');
assert.match(script, /optimisticMessage\.failed = true/, 'failed requests must preserve a retryable message near its context');
assert.match(script, /if \(!state\.draft\.trim\(\)\) state\.draft = content/, 'failed requests must restore the input draft');
assert.match(script, /var previousMessages = dialogue\.querySelector\('\.zq-ai-messages'\)/, 'dialogue rerenders must capture the existing scroll container');
assert.match(script, /var previousScrollDistance = previousMessages/, 'dialogue rerenders must measure the user scroll position');
assert.match(script, /var followLatest = state\.followLatest \|\| !previousMessages \|\| previousScrollDistance <= 72/, 'only bottom-pinned conversations should follow new messages');
assert.match(script, /messages\.style\.scrollBehavior = 'auto'/, 'auto-scroll must not animate from the top after a rerender');
assert.match(script, /data-zq-sidebar-scrim/, 'mobile sidebar must include a backdrop');
assert.match(script, /page\.querySelector\('\[data-zq-sidebar-scrim\]'\)\.addEventListener\('click'/, 'clicking the sidebar backdrop must close it');
assert.match(script, /data-zq-close-sidebar/, 'mobile sidebar must include a close button');
assert.match(script, /aria-label="\\u5173\\u95ed\\u4f1a\\u8bdd\\u5217\\u8868"/, 'sidebar close button must be labelled');
assert.match(script, /event\.key === 'Escape' && state\.sidebarOpen/, 'Escape must close the sidebar');
assert.match(script, /document\.body\.style\.overflow = 'hidden'/, 'opening the sidebar must lock body scrolling');
assert.match(script, /document\.body\.style\.overflow = state\.sidebarBodyLock\.bodyOverflow/, 'closing the sidebar must restore body scrolling');
assert.match(script, /deltaX < -64 && Math\.abs\(deltaX\) > Math\.abs\(deltaY\) \* 1\.25/, 'horizontal swipe must close without stealing ordinary vertical scrolling');
assert.match(script, /function setSidebarOpen\(open, options\)/, 'sidebar state changes must use one lifecycle helper');
assert.match(script, /menu\.setAttribute\('aria-expanded'/, 'sidebar menu must expose its expanded state');
assert.match(script, /menu\.setAttribute\('aria-controls', 'zq-ai-sidebar-panel'\)/, 'sidebar menu must identify the controlled panel');
assert.match(script, /window\.matchMedia\('\(max-width:760px\)'\)\.matches/, 'desktop sidebar must remain accessible while mobile closed state is hidden');
assert.match(script, /window\.removeEventListener\('keydown', state\.sidebarKeyHandler, true\)/, 'route cleanup must remove the sidebar keyboard listener');
assert.match(script, /navigator\.clipboard.*writeText/s, 'copy must prefer the Clipboard API');
assert.match(script, /writeText\(text\)\.catch\(fallbackCopy\)/, 'copy must fall back when the Clipboard API rejects');
assert.match(script, /document\.execCommand\('copy'\)/, 'copy must provide a legacy fallback');
assert.match(script, /function regenerateMessage\(message\)/, 'assistant messages must support real regeneration');
assert.match(script, /sendCurrentMessage\(source\.body, \{ actionMessageId: message\.id, source: 'regenerate' \}\)/, 'regeneration must reuse the real message endpoint');
assert.match(script, /function retryFailedMessage\(message\)/, 'failed messages must expose retry behavior');
assert.match(script, /retryButton\.appendChild\(createMessageIcon\('refresh-cw'\)\)/, 'failed message retry must use a discoverable refresh icon');
assert.match(script, /function createMessageIcon\(name\)/, 'message actions must use shared inline Lucide-style icons');
assert.match(script, /labelMessageAction\(copyButton, copied \? 'check' : 'copy'/, 'copy action must render an icon with status feedback');
assert.match(script, /labelMessageAction\(editButton, 'pencil'/, 'edit action must render a pencil icon');
assert.match(script, /labelMessageAction\(sourceToggle, 'book-open'/, 'source action must render a book icon');
assert.match(script, /labelMessageAction\(deleteButton, deleting \? 'loader-circle' : confirmingDelete \? 'check' : 'trash-2'/, 'delete action must render stateful icons');
assert.match(script, /function editMessage\(message\)/, 'user messages must support editing into the composer');
assert.match(script, /input\.setSelectionRange\(input\.value\.length, input\.value\.length\)/, 'editing must focus the restored draft');
assert.match(script, /function toggleMessageSources\(messageId\)/, 'assistant sources must expand and collapse');
assert.match(script, /sourceToggle\.setAttribute\('aria-expanded'/, 'source toggle must expose expanded state');
assert.match(script, /function deleteMessage\(message\)/, 'single messages must support deletion');
assert.match(script, /confirmMessageDeleteId !== message\.id/, 'single-message deletion must require confirmation');
assert.match(script, /\/messages\/\' \+ encodeURIComponent\(message\.id\)/, 'single-message deletion must call the backend message endpoint');
assert.ok(script.includes("if (!config.configured)"), 'missing model configuration needs a dedicated state');
assert.ok(script.includes('DASHSCOPE_BASE_URL') && script.includes('DASHSCOPE_API_KEY'), 'missing model configuration must be explicit');

assert.equal((server.match(/const aiAssistantScript =/g) || []).length, 1, 'server should declare the script once');
assert.equal((server.match(/aiAssistantScript\];/g) || []).length, 1, 'server should inject the script once');
assert.match(server, /function routeDocumentFor/, 'extensionless routes should resolve their exported HTML document');
assert.match(server, /\['\[id\]', '\[section\]'\]/, 'parameterized route documents should resolve to their exported template');
assert.match(server, /standaloneAssistant/, 'assistant route should use a standalone document');
assert.doesNotMatch(server, /tabsTransitionSource|tabsTransitionPatched/, 'static service must not rewrite the native tab transition');
assert.match(standalonePage, /<body><\/body>/, 'standalone assistant document must not contain pre-rendered chat text');
assert.match(server, /!standaloneAssistant && !html\.includes/, 'standalone assistant document must not load unrelated recommendation enhancements');

console.log(JSON.stringify({ result: 'ok', checks: 88 }));
