const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');

const script = fs.readFileSync(path.join(__dirname, '..', 'dist', 'zhiqu-ai-assistant.js'), 'utf8');
const server = fs.readFileSync(path.join(__dirname, '..', 'serve-static.cjs'), 'utf8');
const standalonePage = fs.readFileSync(path.join(__dirname, '..', 'dist', 'ai-assistant.html'), 'utf8');
const alicePortrait = fs.readFileSync(path.join(__dirname, '..', 'dist', 'ai-assistant-alice.jpg'));
const assistantController = fs.readFileSync(path.join(__dirname, '..', '..', 'server', 'patch-src', 'com', 'zhiqu', 'server', 'assistant', 'AiAssistantController.java'), 'utf8');
const assistantClient = fs.readFileSync(path.join(__dirname, '..', '..', 'server', 'patch-src', 'com', 'zhiqu', 'server', 'assistant', 'AiAssistantClient.java'), 'utf8');
const assistantService = fs.readFileSync(path.join(__dirname, '..', '..', 'server', 'patch-src', 'com', 'zhiqu', 'server', 'assistant', 'AiAssistantService.java'), 'utf8');
const generationRegistry = fs.readFileSync(path.join(__dirname, '..', '..', 'server', 'patch-src', 'com', 'zhiqu', 'server', 'assistant', 'AiAssistantGenerationRegistry.java'), 'utf8');

assert.match(script, /if \(window\.__zhiquAiAssistantLoaded\) return;/, 'script must mount once');
assert.match(script, /data-zq-ai-assistant-page/, 'page needs a unique mount marker');
assert.match(script, /data-zq-ai-global-nav/, 'navigation needs a unique mount marker');

const labels = ["\\u9996\\u9875", "\\u5b66\\u4e60", "AI\\u52a9\\u624b", "\\u793e\\u533a", "\\u6211\\u7684"];
let previous = -1;
for (const label of labels) {
  const position = script.indexOf("label: '" + label + "'");
  assert.ok(position > previous, `navigation item ${label} must appear in the required order`);
  previous = position;
}
assert.match(script, /href: '\/ai-assistant'/, 'assistant route must be /ai-assistant');
assert.match(script, /window\.history\.pushState\(\{\}, '', href\)/, 'top-level navigation should use in-app history transitions');
assert.doesNotMatch(script, /new PopStateEvent\('popstate'\)/, 'assistant navigation must not synthesize an Expo tab transition');
assert.doesNotMatch(script, /if \(pathName\(\) !== href\) window\.location\.assign\(href\)/, 'top-level navigation must not hard reload the full bundle');
assert.match(script, /if \(href !== '\/ai-assistant'\) \{[^}]*window\.location\.assign\(href\)/s, 'standalone assistant navigation should retain a static fallback');
assert.match(script, /function activateOriginalNav/, 'existing top-level navigation handlers should be reused');
assert.match(script, /if \(activateOriginalNav\(item\.label, function \(\) \{/, 'non-assistant tabs should delegate to the native router');
assert.match(script, /state\.nativeRoute === item\.href && pathName\(\) === '\/ai-assistant'/, 'returning to the native page underneath the assistant should use browser history');
assert.match(script, /window\.history\.back\(\)/, 'assistant-to-underlying-tab navigation should use the native history entry');
assert.match(script, /function detachAssistantOverlay/, 'assistant overlay should be removed before a native tab transition');
assert.match(script, /state\.leavingAssistant && isAssistantRoute\(\)/, 'route synchronization should not remount the assistant during its native transition');
assert.match(script, /translateY\(-8px\)/, 'active assistant icon must rise 8px');
assert.match(script, /\.zq-ai-page\{[^}]*animation:none\}/, 'assistant page should not animate when entered from another page');
assert.match(script, /@keyframes zqAiPageEnter/, 'assistant page enter keyframes must exist');
assert.match(script, /function replayNativePageEnter/, 'returning to the native page underneath the assistant should replay the native scene transition');
assert.match(script, /#root\.zq-ai-native-page-enter/, 'the native shell replay should use the same page transition');
assert.match(script, /perspective\(1400px\) rotateY\(-96deg\) scale\(\.985\)/, 'assistant page should reuse the existing tabs enter rotation, scale and perspective');
assert.doesNotMatch(script, /zqAiPageFade|zqAiPageFlip/, 'assistant page must not use a separate page transition');
assert.doesNotMatch(script, /translateX\(24px\)/, 'assistant page must not invent a separate slide transition');
assert.match(script, /\.zq-ai-nav-item\[data-active="true"\] \.zq-ai-nav-icon\{width:44px;height:44px/, 'every active navigation icon must share the assistant scale effect');
assert.match(script, /\.zq-ai-nav-item:not\(\[data-active="true"\]\):hover \.zq-ai-nav-icon/, 'every inactive navigation icon must share the hover lift effect');
assert.match(script, /createAssistantNavIcon/, 'assistant navigation must use the Lucide Sparkles fallback icon');
assert.match(script, /M11\.017 2\.814a1 1 0 0 1 1\.966 0/, 'assistant icon must use the bundled Lucide Sparkles path');
assert.match(script, /messages-square/, 'community navigation must use the MessagesSquare icon');
assert.match(script, /M16 10a2 2 0 0 1-2 2H6\.828/, 'community navigation must use the native MessagesSquare path');
assert.match(script, /user-round/, 'profile navigation must use the UserRound icon');
assert.match(script, /M20 21a8 8 0 0 0-16 0/, 'profile navigation must use the native UserRound path');
assert.match(script, /@media\(prefers-reduced-motion:reduce\)/, 'reduced motion must be supported');
assert.match(script, /min-height:52px/, 'navigation target must be at least 48px');
assert.match(script, /height:66px/, 'navigation should retain the original compact bar height');
assert.match(script, /border-radius:24px/, 'navigation should retain the original floating-bar radius');
assert.match(script, /rgba\(255,253,250,\.76\)/, 'navigation should retain the original translucent surface');
assert.match(script, /\.zq-ai-shell\{[^}]*padding-bottom:var\(--zq-ai-nav-height\)/, 'content must reserve navigation space while the page background covers the viewport');

assert.doesNotMatch(script, /QuickPromptList|presetQuestions|quickReplies/, 'preset prompt components are forbidden');
assert.doesNotMatch(script, /\u5efa\u8bae\u95ee|\u8bd5\u8bd5\u95ee|\u5feb\u6377\u56de\u590d/, 'preset question copy is forbidden');
assert.match(script, /\/api\/assistant\/config/, 'config endpoint must be used');
assert.match(script, /\/api\/assistant\/conversations/, 'conversation endpoint must be used');
assert.match(script, /\/api\/assistant\/feedback/, 'feedback endpoint must be used');
assert.match(script, /function refreshSession\(currentSession\)/, 'assistant API requests must refresh expired access tokens');
assert.match(script, /response\.status === 401 && retryAfterRefresh !== false/, 'assistant API requests must retry once after a 401');
assert.match(script, /state\.deletingId = id/, 'conversation deletion must expose an in-flight state');
assert.match(script, /var cancel = state\.loading && state\.activeConversationId === id[\s\S]*cancelActiveGeneration\(\{ silent: true, skipRender: true \}\)/, 'conversation deletion must cancel only the deleted conversation in flight');
assert.match(script, /state\.activeConversationId = null;[\s\S]*state\.messages = \[\];[\s\S]*state\.draft = '';[\s\S]*renderDialogue\(\);/, 'deleting the active conversation must leave a truthful empty state');
assert.doesNotMatch(script.match(/function deleteConversation\(id\) \{[\s\S]*?\n  \}\n\n  function deleteMessage/)?.[0] || '', /return createConversation\(\)/, 'deleting a conversation must not silently create a replacement conversation');
assert.match(script, /deleteButton\.disabled = !!state\.deletingId/, 'conversation deletion must prevent duplicate clicks');
assert.match(script, /deleteButton\.textContent = deleting \? '\\u5220\\u9664\\u4e2d\\u2026'/, 'conversation deletion must show progress feedback');
assert.match(script, /state\.authRequired = isAuthError\(error\)/, 'expired authentication must be distinguishable from other delete failures');
assert.match(script, /className = 'zq-ai-error-action'/, 'expired authentication must offer a re-login action');
assert.match(script, /function beginConversationTransition\(\)/, 'new conversations must expose a transition state');
assert.match(script, /zqAiConversationSwitch/, 'new conversations must provide a visible switch animation');
assert.match(script, /state\.loadingLabel = animate \? '\\u6b63\\u5728\\u521b\\u5efa\\u65b0\\u5bf9\\u8bdd' : ''/, 'new conversations must explain the transition while being created');
assert.match(script, /function titleFromFirstMessage\(message\)/, 'conversation titles must derive from the first user message');
assert.match(script, /if \(firstUserMessage\) applyFirstMessageTitle\(userMessage\)/, 'first-message titles must update the sidebar after sending');
assert.match(script, /state\.draft = ''/, 'draft should clear after the message is placed into the chat');
assert.match(script, /AbortController/, 'stop generation must abort the active request');
assert.match(script, /function cancelActiveGeneration\(options\)/, 'generation cancellation must use one frontend lifecycle helper');
assert.match(script, /\/api\/assistant\/requests\/.*encodeURIComponent\(active\.requestId\)/, 'stop generation must call the authenticated backend cancellation endpoint');
assert.match(script, /startGenerationRequest\(requestId, 'create-conversation'\)/, 'new-conversation greetings must register a cancellable request');
assert.match(script, /body: \{ requestId: requestId, memoryEnabled: state\.memoryEnabled \}/, 'new conversations must send their cancellation request ID');
assert.match(script, /stop\.disabled = state\.generationCancelPending/, 'stop generation must prevent duplicate cancellation clicks');
assert.match(script, /var optimisticMessage = retryMessage \|\| \{/, 'sent text must enter the chat before generation starts');
assert.match(script, /state\.messages\.push\(optimisticMessage\)/, 'sent text must render as an immediate user message');
assert.match(script, /state\.latestMessageId = optimisticMessage\.id/, 'new user messages must receive a one-time animation marker');
assert.match(script, /data-entering/, 'new chat bubbles must expose an animation state');
assert.match(script, /@keyframes zqAiMessageIn/, 'chat bubbles must animate into the conversation');
assert.match(script, /zqAiMessageIn 560ms ease-out/, 'chat bubble animation must remain readable');
assert.match(script, /scale\(\.82\)/, 'chat bubbles must visibly grow from a smaller size');
assert.match(script, /transform-origin:bottom right/, 'user chat bubbles must grow from their lower corner');
assert.match(script, /transform-origin:bottom left/, 'assistant chat bubbles must grow from their lower corner');
assert.match(script, /optimisticMessage\.failed = true/, 'failed requests must preserve a retryable message near its context');
assert.match(script, /if \(!state\.draft\.trim\(\)\) state\.draft = content/, 'failed requests must restore the input draft');
assert.match(script, /var previousMessages = dialogue\.querySelector\('\.zq-ai-messages'\)/, 'dialogue rerenders must capture the existing scroll container');
assert.match(script, /var previousScrollDistance = previousMessages/, 'dialogue rerenders must measure the user scroll position');
assert.match(script, /var followLatest = state\.followLatest \|\| !previousMessages \|\| previousScrollDistance <= 72/, 'only bottom-pinned conversations should follow new messages');
assert.match(script, /messages\.style\.scrollBehavior = 'auto'/, 'auto-scroll must not animate from the top after a rerender');
assert.match(script, /data-zq-sidebar-scrim/, 'mobile sidebar must include a backdrop');
assert.match(script, /page\.querySelector\('\[data-zq-sidebar-scrim\]'\)\.addEventListener\('click'/, 'clicking the sidebar backdrop must close it');
assert.match(script, /data-zq-close-sidebar/, 'mobile sidebar must include a close button');
assert.match(script, /aria-label="\\u5173\\u95ed\\u4f1a\\u8bdd\\u5217\\u8868"/, 'sidebar close button must be labelled');
assert.match(script, /event\.key === 'Escape' && state\.sidebarOpen/, 'Escape must close the sidebar');
assert.match(script, /document\.body\.style\.overflow = 'hidden'/, 'opening the sidebar must lock body scrolling');
assert.match(script, /document\.body\.style\.overflow = state\.sidebarBodyLock\.bodyOverflow/, 'closing the sidebar must restore body scrolling');
assert.match(script, /deltaX < -64 && Math\.abs\(deltaX\) > Math\.abs\(deltaY\) \* 1\.25/, 'horizontal swipe must close without stealing ordinary vertical scrolling');
assert.match(script, /function setSidebarOpen\(open, options\)/, 'sidebar state changes must use one lifecycle helper');
assert.match(script, /SIDEBAR_COLLAPSED_KEY = 'zq:ai-assistant-sidebar-collapsed:v1'/, 'desktop sidebar preference must use a stable storage key');
assert.match(script, /sidebarCollapsed: readSidebarCollapsed\(\)/, 'desktop sidebar preference must be restored on page load');
assert.match(script, /data-zq-toggle-sidebar/, 'desktop sidebar must expose a collapse control');
assert.match(script, /aria-label="\\u6536\\u8d77\\u4f1a\\u8bdd\\u5217\\u8868" aria-expanded="true" aria-controls="zq-ai-sidebar-panel"/, 'desktop collapse control must expose its state and target');
assert.match(script, /function setSidebarCollapsed\(collapsed, options\)/, 'desktop sidebar state changes must use one lifecycle helper');
assert.match(script, /localStorage\.setItem\(SIDEBAR_COLLAPSED_KEY, collapsed \? '1' : '0'\)/, 'desktop sidebar preference must persist across refreshes');
assert.match(script, /data-sidebar-collapsed="true"\]\{grid-template-columns:68px minmax\(0,1fr\)\}/, 'collapsed desktop sidebar must become a compact rail');
assert.match(script, /data-sidebar-collapsed="true"\] \.zq-ai-conversation-list\{display:none\}/, 'collapsed desktop rail must hide conversation labels');
assert.match(script, /zq-ai-icon-button\.zq-ai-sidebar-toggle\{display:none\}/, 'mobile layout must keep using its existing drawer control');
assert.match(script, /menu\.setAttribute\('aria-expanded'/, 'sidebar menu must expose its expanded state');
assert.match(script, /menu\.setAttribute\('aria-controls', 'zq-ai-sidebar-panel'\)/, 'sidebar menu must identify the controlled panel');
assert.match(script, /window\.matchMedia\('\(max-width:760px\)'\)\.matches/, 'desktop sidebar must remain accessible while mobile closed state is hidden');
assert.match(script, /window\.removeEventListener\('keydown', state\.sidebarKeyHandler, true\)/, 'route cleanup must remove the sidebar keyboard listener');
assert.match(script, /navigator\.clipboard.*writeText/s, 'copy must prefer the Clipboard API');
assert.match(script, /writeText\(text\)\.catch\(fallbackCopy\)/, 'copy must fall back when the Clipboard API rejects');
assert.match(script, /document\.execCommand\('copy'\)/, 'copy must provide a legacy fallback');
assert.match(script, /function regenerateMessage\(message\)/, 'assistant messages must support real regeneration');
assert.match(script, /regenerateMessage\(message\)[\s\S]*?method: 'PUT'[\s\S]*?content: source\.body/, 'regeneration must update the original user exchange through the real backend');
assert.match(script, /regenerateMessage\(message\)[\s\S]*?replaceEditedExchange\(source\.id, exchange\)/, 'regeneration must replace the existing assistant reply in place');
assert.doesNotMatch(script, /sendCurrentMessage\(source\.body, \{[^}]*source: 'regenerate'/, 'regeneration must not append another user message through the send flow');
assert.match(script, /function retryFailedMessage\(message\)/, 'failed messages must expose retry behavior');
assert.match(script, /retryButton\.appendChild\(createMessageIcon\('refresh-cw'\)\)/, 'failed message retry must use a discoverable refresh icon');
assert.match(script, /function createMessageIcon\(name\)/, 'message actions must use shared inline Lucide-style icons');
assert.match(script, /\.zq-ai-message-icon,\.zq-ai-source-icon\{position:relative;z-index:1;/, 'message icons must remain above their hover and focus background');
assert.match(script, /aliceMode \? '\/ai-assistant-alice\.jpg' : '\/ai-assistant-portrait\.webp'/, 'assistant stage must switch between the two supplied portrait assets');
assert.match(script, /portrait\.alt = aliceMode[\s\S]*?'\\u9690\\u85cf\\u5bf9\\u8bdd/, 'hidden portrait asset must remain accessible');
assert.ok(alicePortrait.length > 0, 'hidden portrait image must be packaged in the static build');
assert.match(script, /var PORTRAIT_TRIGGER = '\\u5fcd\\u51ac2033'/, 'portrait easter egg must use the exact trigger text');
assert.match(script, /var ALICE_TRIGGER = '\\u5fc3\\u7231\\u7684\\u5c11\\u5973\\u5728\\u54ea\\u91cc\\uff1f'/, 'hidden persona must use the exact activation text');
assert.match(script, /portrait\.hidden = !state\.portraitVisible/, 'portrait must be hidden by default');
assert.match(script, /if \(content === ALICE_TRIGGER\) setPortraitMode\('alice'\)/, 'submitting the hidden trigger must reveal its image without waiting for the AI reply');
assert.match(script, /function syncPortraitFromMessages\(\)[\s\S]*?if \(content === ALICE_TRIGGER\) mode = 'alice'/, 'portrait mode must be restored from the active conversation messages');
assert.match(script, /\.zq-ai-portrait\[data-mode="alice"\]\{[^}]*object-fit:contain/, 'hidden image must fit inside the stage image region');
assert.match(script, /function openConversation\(id\) \{[\s\S]*?setPortraitVisible\(false\)/, 'switching conversations must hide the portrait');
assert.match(script, /labelMessageAction\(copyButton, copied \? 'check' : 'copy'/, 'copy action must render an icon with status feedback');
assert.match(script, /wrapper\.appendChild\(bubble\);[\s\S]*?wrapper\.appendChild\(actions\);/, 'message actions must render outside the message bubble');
assert.doesNotMatch(script, /bubble\.appendChild\(actions\)/, 'message actions must not be nested inside the message bubble');
assert.match(script, /actions\.append\(helpful, notHelpful\)/, 'assistant feedback buttons must share the primary message action row');
assert.doesNotMatch(script, /zq-ai-feedback/, 'assistant feedback must not render in a separate second row');
assert.match(script, /\.zq-ai-input\{[^}]*overflow-y:auto;scrollbar-width:none;-ms-overflow-style:none/, 'assistant input must keep scrolling without showing a native scrollbar');
assert.match(script, /\.zq-ai-input::-webkit-scrollbar\{width:0;height:0;display:none\}/, 'assistant input must hide the WebKit scrollbar');
assert.match(script, /labelMessageAction\(editButton, 'pencil'/, 'edit action must render a pencil icon');
assert.match(script, /labelMessageAction\(sourceToggle, 'book-open'/, 'source action must render a book icon');
assert.doesNotMatch(script, /labelMessageAction\(deleteButton/, 'message actions must not render per-message deletion');
assert.doesNotMatch(script, /actions\.appendChild\(deleteButton\)/, 'message action rows must not include a delete button');
assert.doesNotMatch(script, /'trash-2'/, 'the assistant message toolbar must not package a trash icon');
assert.match(script, /function editMessage\(message\)[\s\S]*?state\.editingMessageDraft = message\.body \|\| ''/, 'user messages must enter an inline bubble editor');
assert.doesNotMatch(script, /function editMessage\(message\)[\s\S]*?state\.draft = message\.body/, 'inline editing must not overwrite the bottom composer draft');
assert.match(script, /editInput\.className = 'zq-ai-inline-editor'/, 'editing must render a textarea inside the original bubble');
assert.match(script, /editCancel\.textContent = '\\u53d6\\u6d88'/, 'inline editor must provide a cancel command');
assert.match(script, /editSubmit\.textContent = state\.loading \? '\\u751f\\u6210\\u4e2d' : '\\u53d1\\u9001'/, 'inline editor must provide a stateful send command');
assert.match(script, /event\.key === 'Escape'[\s\S]*?cancelEditMessage\(\)/, 'Escape must cancel inline editing');
assert.match(script, /event\.key === 'Enter' && \(event\.ctrlKey \|\| event\.metaKey\)/, 'Ctrl or Command plus Enter must submit inline editing');
assert.match(script, /function latestUserMessageId\(\)[\s\S]*?message\.id === latestUserMessageId\(\)/, 'only the latest user message may expose the edit action');
assert.match(script, /method: 'PUT'[\s\S]*?content: content[\s\S]*?memoryEnabled: state\.memoryEnabled/, 'edited content must use the real backend PUT endpoint');
assert.match(script, /function replaceEditedExchange\(messageId, exchange\)[\s\S]*?state\.messages\.splice\(userIndex, 1, userMessage\)[\s\S]*?state\.messages\.splice\(assistantIndex, 1, assistantMessage\)/, 'successful editing must replace the original pair in place');
assert.match(script, /state\.editingMessageError = error\.name === 'AbortError'[\s\S]*?: messageForError\(error/, 'failed editing must keep a recoverable inline error');
assert.match(script, /bubble\.appendChild\(editForm\);[\s\S]*?wrapper\.appendChild\(bubble\);[\s\S]*?return wrapper;/, 'editing must hide the external action row until editing ends');
assert.match(script, /input\.disabled = !!state\.editingMessageId/, 'bottom composer must be disabled while a bubble is being edited');
assert.match(script, /function toggleMessageSources\(messageId\)/, 'assistant sources must expand and collapse');
assert.match(script, /sourceToggle\.setAttribute\('aria-expanded'/, 'source toggle must expose expanded state');
assert.ok(script.includes("if (!config.configured)"), 'missing model configuration needs a dedicated state');
assert.ok(script.includes('DASHSCOPE_BASE_URL') && script.includes('DASHSCOPE_API_KEY'), 'missing model configuration must be explicit');

assert.equal((server.match(/const aiAssistantScript =/g) || []).length, 1, 'server should declare the script once');
assert.equal((server.match(/aiAssistantScript\];/g) || []).length, 1, 'server should inject the script once');
assert.match(server, /function routeDocumentFor/, 'extensionless routes should resolve their exported HTML document');
assert.match(server, /\['\[id\]', '\[section\]'\]/, 'parameterized route documents should resolve to their exported template');
assert.match(server, /standaloneAssistant/, 'assistant route should use a standalone document');
assert.doesNotMatch(server, /tabsTransitionSource|tabsTransitionPatched/, 'static service must not rewrite the native tab transition');
assert.match(standalonePage, /<body><\/body>/, 'standalone assistant document must not contain pre-rendered chat text');
assert.match(server, /!standaloneAssistant && !standaloneSinglePlayer && !html\.includes/, 'standalone assistant document must not load unrelated recommendation enhancements');
assert.match(assistantController, /@DeleteMapping\("\/requests\/\{requestId\}"\)/, 'backend must expose an authenticated cancellation endpoint');
assert.match(assistantClient, /httpClient\.sendAsync/, 'provider generation must use a cancellable asynchronous HTTP request');
assert.match(assistantClient, /private ApiException providerFailure\(int statusCode, String responseBody\)/, 'provider failures must be classified before reaching the generic UI message');
assert.match(assistantClient, /AI_MODEL_ACCESS_DENIED/, '403 provider responses must expose a model authorization error');
assert.match(assistantClient, /当前 AI 模型未获授权/, 'model authorization failures must tell the user what to configure');
assert.match(generationRegistry, /request\.cancel\(true\)/, 'server cancellation must cancel the active provider future');
assert.match(assistantService, /generation\.throwIfCancelled\(\)[\s\S]*?insertAssistantMessage/, 'server must recheck cancellation before saving an assistant reply');
assert.match(generationRegistry, /CANCEL_TTL_MILLIS = Duration\.ofMinutes\(1\)\.toMillis\(\)/, 'server must handle cancellation arriving before generation registration');

console.log(JSON.stringify({ result: 'ok', checks: 135 }));
